export const SET_COMPANY_STATS = "SET_COMPANY_STATS"
export const SET_CURR_COMPANY = "SET_CURR_COMPANY"
export const SET_CURR_STOCK = "SET_CURR_STOCK"
export const SET_START = "SET_START"
export const SET_END = "SET_END"