export const SAVE_USER = "SAVE_USER"
export const UPDATE_USER = "UPDATE_USER"
export const DELETE_USER = "DELETE_USER"
export const SET_USER_LIST = "SET_USER_LIST"
export const SET_CURR_USER = "SET_CURR_USER"
